-- DROP SEQUENCE --
DROP SEQUENCE R_NO_SEQ;
DROP SEQUENCE OD_NO_SEQ;
DROP SEQUENCE O_NO_SEQ;
DROP SEQUENCE W_NO_SEQ;
DROP SEQUENCE WD_NO_SEQ;
DROP SEQUENCE P_NO_SEQ;

-- DROP TABLE --
DROP TABLE REVIEWS CASCADE CONSTRAINTS; 
DROP TABLE ORDERS_DETAIL CASCADE CONSTRAINTS; 
DROP TABLE ORDERS CASCADE CONSTRAINTS; 
DROP TABLE WISHLIST CASCADE CONSTRAINTS; 
DROP TABLE WISHLIST_DETAIL CASCADE CONSTRAINTS; 
DROP TABLE MEMBER CASCADE CONSTRAINTS; 
DROP TABLE PRODUCT CASCADE CONSTRAINTS; 