/* ORDERS_DETAIL */

DROP SEQUENCE ORDERS_DETAIL_NO_SEQ;
DROP TABLE ORDERS_DETAIL CASCADE CONSTRAINTS; 

CREATE TABLE ORDERS_DETAIL (
	od_no NUMBER(10) NOT NULL PRIMARY KEY, /* 주문상세번호 */
	od_o_no NUMBER(10) REFERENCES ORDERS(o_no), /* 주문번호 */
	od_p_no NUMBER(10), /* 상품번호 */
	od_amount NUMBER(10), /* 상품수량 */
	od_price NUMBER(10) /* 상품금액 */
);
CREATE SEQUENCE OD_NO_SEQ INCREMENT BY 1 START WITH 1;

COMMIT;
