/* WISHLIST_DETAIL */

DROP SEQUENCE WISHLIST_DETAIL_NO_SEQ;
DROP TABLE WISHLIST_DETAIL CASCADE CONSTRAINTS; 


CREATE TABLE WISHLIST_DETAIL (
	wd_no NUMBER(10) NOT NULL PRIMARY KEY, /* 위시리스트상세번호 */
	wd_w_no NUMBER(10) REFERENCES WISHLIST(w_no), /* 위시리스트번호 */
	wd_p_no NUMBER(10) REFERENCES PRODUCT(p_no), /* 상품번호 */
	wd_amount NUMBER(10), /* 상품수량 */
	wd_price NUMBER(10) /* 상품금액 */
);
CREATE SEQUENCE WD_NO_SEQ INCREMENT BY 1 START WITH 1;

COMMIT;