/* WISHLIST */

DROP SEQUENCE WISHLIST_NO_SEQ;
DROP TABLE WISHLIST_DETAIL CASCADE CONSTRAINTS; 


CREATE TABLE WISHLIST (
	w_no NUMBER(10) NOT NULL PRIMARY KEY, /* 위시리스트번호 */
	w_m_id VARCHAR2(20) REFERENCES MEMBER(m_id)/* 회원아이디 */
);
CREATE SEQUENCE W_NO_SEQ INCREMENT BY 1 START WITH 1;

COMMIT;